### ISSUE TITLE
The client cannot work in a three-node ETCD cluster if one node is stoped

### ISSUE THREAD

**Issue by chenhui0228** [etcdv3/etcd-client#12]
Three-node ETCD cluster if only two nodes are alive.The client instance has an error.

status: Unknown, message: "Service was not ready: transport error: buffered service failed: load balancer discovery error: error trying to connect: tcp connect error: Connection refused (os error 111)", details: [], metadata: MetadataMap { headers: {} }

Are you considering implementing health-check to automatically insert and remove unavailable nodes

**Comment by davidli2010** [comment]
`etcd-client` is just a rust wrapper of `etcd` gRPC API. We want to keep it simple.
It's your responsibility to handle the etcd cluster problem.
