### ISSUE TITLE
Get as Mutable methods

### ISSUE THREAD

**Issue by tiagolobocastro** [etcdv3/etcd-client#17]
Hi,

Seems get/put/delete are all mutable methods, was this intended, even for the get?

Thanks

**Comment by davidli2010** [comment]
Yes, beacause the inner client auto-generated by prost need mutable.

**Comment by tiagolobocastro** [comment]
Ah fair enough.. 
So, does this mean we can only issue 1 request at a time?

**Comment by davidli2010** [comment]
> Ah fair enough..
> So, does this mean we can only issue 1 request at a time?

The client can be cloned，so you can have many clients.

This weekend I will release v0.6.2. In this version, you can get separate operation clients from client. It’s lightweight.

**Comment by tiagolobocastro** [comment]
Btw, if I clone a client and do a watch via that clone, will the watch be "dropped" once the cloned client is dropped, or will it be alive as long as the original client is alive?

**Comment by davidli2010** [comment]
In my experiment, the Watcher and WatchStream still work after the client is dropped.

**Comment by davidli2010** [comment]
In my experiment, the Watcher and WatchStream still work after the client is dropped.

**Comment by davidli2010** [comment]
v0.6.2 is released :-)

**Comment by tiagolobocastro** [comment]
Thanks I'll have a look at the new version!
I'm testing the watch and seems that if I kill the etcd server the watch starts failing with "error reading a body from connection: broken pipe" and it never recovers even if I restart the etcd. Is this expected?

**Comment by davidli2010** [comment]
Yes, you should reconnect to etcd by yourself.

**Comment by tiagolobocastro** [comment]
You mean I would have to connect a new client and issue a new watch?

**Comment by davidli2010** [comment]
I think so.

**Comment by tiagolobocastro** [comment]
Well, the client itself seems to still be able to connect if I bring etcd back online. Is this just luck or can I rely on this? Otherwise I need to create an overlay over this client to reconnect.

**Comment by davidli2010** [comment]
I think you can rely on this, but I'm not sure. gRPC use HTTP/2, I'm not familiar with it. 

gRPC will load balance accross all the provided endpoints. You can test it.
