### ISSUE TITLE
Enhancement: Add with_prefix() to DeleteOptions 

### ISSUE THREAD

**Issue by yarncraft** [etcdv3/etcd-client#20]
Add the **with_prefix** behavior to the DeleteOptions

Example:
`DeleteOptions::new().with_prefix();`

**Comment by davidli2010** [comment]
DeleteOptions  is enhanced in [0.6.5](https://docs.rs/etcd-client/0.6.5/etcd_client/struct.DeleteOptions.html).

**Comment by yarncraft** [comment]
> DeleteOptions is enhanced in [0.6.5](https://docs.rs/etcd-client/0.6.5/etcd_client/struct.DeleteOptions.html).

Thank you!!
