### ISSUE TITLE
Enhancement: Allow external libraries to instantiate *Response types for mocking

### ISSUE THREAD

**Issue by g-murzik** [etcdv3/etcd-client#22]
Hi,

I would like to use `etcd-client` in a project of mine. The project should also come with some unit tests where the (wrapped) interaction with `etcd-client` is mocked via [mockall](https://docs.rs/mockall/0.10.1/mockall/). I face however some issues with the return types such as `GetResponse` or `PutResponse`, because I am not able to create an 'instance' of those responses (which should be returned by the mock object) on my own.

It would be cool to optionally expose the related, internal protobuf representations and make the constructor functions such as `GetResponse::new` public to allow such use cases.

I have already prepared the first part [here](https://github.com/g-murzik/etcd-client/commit/e9125da3661a3225bd95eddb7b5f564e454c0511). Now, only the public constructor functions are missing. I image some more conditional compilation leveraging your [`visible`](https://github.com/davidli2010/visible) crate, which avoids large modifications to the code base like this:

```rust
// inside src/rpc/kv.rs
impl PutResponse {
    /// Create a new `PutResponse` from pb put response.
    #[cfg_attr(protobuf-response-structs, visible::Function(pub))]
    #[inline]
    const fn new(resp: PbPutResponse) -> Self {
        Self(resp)
    }
...
}
```

@davidli2010 What do you think about the approach, do you support the idea?

**Comment by davidli2010** [comment]
You mentioned `visible`, this crate is used to change field visibility. I originally developed `visible` to solve [this problem](https://github.com/tokio-rs/prost/pull/390).

The core problem is we cannot set  fields' visibility for prost generated struts. So we encapsulate all the structs in `etcd-client`.
I have planned to remove redundant encapsulation for prost generated structs by using `visible`.

I think we can start from *Response types, using `visible` to control field visibility with a `pub-field` feature.

**Comment by g-murzik** [comment]
I have tried to integrate your ideas in the PR. Please feel free to comment on anything / suggest any changes there. Thanks in advance!
