### ISSUE TITLE
The inner representation of `KeyValue` couldn't be exported by `pub-response-field`

### ISSUE THREAD

**Issue by YuJuncen** [etcdv3/etcd-client#26]
Hi! I get some trouble when I'm going to access the internal prost field of `KeyValue`:

https://github.com/etcdv3/etcd-client/blob/be00b16618a1f713683e5c8654b6f2782b906e4b/src/rpc/mod.rs#L70-L74

It seems that the field was exported by `#[cfg_attr(feature = "pub-field", visible::StructFields(pub))]`, which (I guess) is omitted in the procedure of https://github.com/etcdv3/etcd-client/pull/23#issuecomment-881813610. May I provide a PR for fixing it?

**Comment by davidli2010** [comment]
> Hi! I get some trouble when I'm going to access the internal prost field of `KeyValue`:
> 
> https://github.com/etcdv3/etcd-client/blob/be00b16618a1f713683e5c8654b6f2782b906e4b/src/rpc/mod.rs#L70-L74
> 
> It seems that the field was exported by `#[cfg_attr(feature = "pub-field", visible::StructFields(pub))]`, which (I guess) is omitted in the procedure of [#23 (comment)](https://github.com/etcdv3/etcd-client/pull/23#issuecomment-881813610). May I provide a PR for fixing it?

Of course, please feel free to create a PR.
