### ISSUE TITLE
Adding more keys to a watch

### ISSUE THREAD

**Issue by diggyk** [etcdv3/etcd-client#33]
The documentation makes it seem like I can watch additional keys on the same watcher but I don't see where or how that would work.  I don't want to create multiple watch streams so I'd prefer to just have one set of channels to and from Etcd.  Is that possible?

**Comment by diggyk** [comment]
Looks like I can do this if we change the watch client to be more open ended.  Instead of `etcd-client` creating a `Watcher` per watch request, if it would just expose the streams so I could send and handle my own watch requests, I think that would work.  I could hand it a clone of the sender stream and just watch for and manage my own list of watch ids.  What do you think?

**Comment by davidli2010** [comment]
Currently we can use WatchOptions to specify key range(prev_key, from_key, prefix, all keys). Is this meets your needs?

**Comment by rrichardson** [comment]
I could certainly see how adding a `watch` method to the Watcher would be useful, calling watch on the returned watcher object would add more subscriptions to the WatcherStream that had already been returned.  

This might be non-trivial to execute in practice, though. An Etcd Watch is the creation of a new gRPC Streaming function call.  (which is a new HTTP2 Stream in the session under the hood)  
This means that you'd basically need to pass all Watch streams into the same Muxxing point where they are then redistributed to the subscribing stream, thus creating a sort of  a mini pubsub system within that `Watcher` or in the `Client`. 

I have similar needs, in that I need to subscribe to a dynamic list of keys,  (however I learn those keys once at startup) 
For that, I use  Tokio's StreamMap.. e.g. 

```rust 
      let mut subs: StreamMap<
          String,
          std::pin::Pin<Box<dyn Stream<Item = PipelineEvent> + Send>>,
      > = StreamMap::new();

      for (key, _) in self.data_keyed_tasks.iter() {
          debug!(key=?key, "subscribing to data prereq key");
          let kvstream = client
              .watch(key.as_bytes(), None)
              .await?
              .map(PipelineEvent::from);
          let _ = subs.insert(
              key.to_owned(),
              Box::pin(Box::new(kvstream))
                  as std::pin::Pin<Box<dyn Stream<Item = PipelineEvent> + Send>>,
          );
      }
...
enum PipelineEvent {
  Data(KvEvent), 
  Task(KvEvent) 
} 

impl From<PbWatchResponse> for PipelineEvent{ 
  fn from(r: PbWatchResponse) -> Self {
     // parse bits out of Watch response
  }
}
```

**Comment by LizardWizzard** [comment]
I'm interested in such an API too. Usual watch create routine waits for watch create response before returning to the caller. If I add `watch()` method to Watcher there is no access to the channel to get watch_id. One possible option is to generate watch_id on the caller's side and provide it through `WatchOptions.with_watch_id`. Some workaround is probably possible with `pub-response-field` feature, but I failed to make it work due to `.with_key` method of WatchOptions being private. Raw proto structures are hidden behind private rpc module too.

What would be an acceptable solution in this case? I can try to make a PR. But need some guidance regarding desired solution

**Comment by rrichardson** [comment]
Maybe the correct answer is to construct the Watcher object first, eg `Client::create_watcher(&self) -> Watcher` , 
 then the watch interface  `Watcher::watch(&mut self, key, options) -> (WatchId, WatchStream)` would store the watch_id in a map internally, and also return it to the caller,  so  so `cancel(&mut self, watch_id: WatchId)`  would work as expected.  
 
 The other option, that might be more ergonomic for some that just want to process a single stream in a loop, is have 
 
 `Client::watch(..) -> (Watcher, WatchStream) `  
 
then any calls to Watcher::watch() would just merge in the new watch stream to the WatchStream that it was returned with.  This would mean that we'd have to mux in the current and future streams into a custom Stream, but that shouldn't be too hard.

**Comment by LizardWizzard** [comment]
> This would mean that we'd have to mux in the current and future streams into a custom Stream

Do you mean that messages would be distributed according to watch_id to a per watch_id channel on the library side? May be quite convenient for some people. 

One thing to note, the current implementation eats `WatchCreateResponse` so, for consistency, it would be better to implement the same behavior for subsequent watches if possible.

Also, it may not be desirable behavior for some of the users. For example, for my use case, it is simpler to receive all messages through one channel and `match` around returned key.

>  is to construct the Watcher object first

Then there won't be a watch_id if the caller didn't supply it. So Watcher::watch_id needs to return Option, an API change that may be undesirable.

Maybe a new primitive can be more flexible. Something like WatchGroup. But it is a divergence from the original etcd API.

**Comment by rrichardson** [comment]
> Then there won't be a watch_id if the caller didn't supply it. So Watcher::watch_id needs to return Option, an API change that may be undesirable.
> Maybe a new primitive can be more flexible. Something like WatchGroup. But it is a divergence from the original etcd API. 

I would have the Watcher::watch method create and return the watch_id in all cases. I guess if the user wants to specify the watch_id, they can make the `watch` method take an Option<WatchId> 

The only other etcd3 interface I'm familiar with is the typescript one from Microsoft.   In that one, there is a single "stream" (actually an event emitter)  so no matter how many times you call it, all events come across that same stream (event) interface. 
It is terribly convenient.  I could definitely see how such behavior would be desirable. 

Keeping track of watch-ids and cancelling is still a challenge, though. 

As you mention, a WatchGroup might be a nice add-on. We could have it do the muxxing of all streams. It could be a completely separate utility that could just  have new WatchStreams added-to and removed-from it.

**Comment by davidli2010** [comment]
Hi all, I open a PR #37 to enhance Watcher. There are two new methods: `Watcher::watch` and `Watcher::cancel_by_id` with specified `watch_id`. 
You can see how to use the two methods in `watch` example.

The basic idea of this PR is to extend `Watcher` and keep the compatiblity.

Alternatively, we can design a new `WatchGroup` API to separate from the single key `Watcher`. We can discuss it based on the PR.

**Comment by rrichardson** [comment]
I misunderstood the etcd3 spec.  For some reason I thought the Watch gRPC response was a 1-direction Stream not a BiDi Stream.  But I am wrong.  This is much easier that I thought, as @davidli2010's PR points out. 

https://etcd.io/docs/v3.2/learning/api/#watch-streams 

As long as we keep hold of that returned BiDi Watch Stream, we can subsequently send additional subscriptions to that same Stream, and it will multiplex multiple requests over that stream (differentiated by watch-id)  

So the requested implementation is basically already done, modulo the ability to make additional requests.

**Comment by LizardWizzard** [comment]
I like the way how it is implemented in the PR. I think this is the best solution for flexibility/given compatibility constraints, it lets the client handle everything without changing the library. Thanks, @davidli2010! Excited to see a new version with your PR being merged to be released to crates.io :)

> modulo the ability to make additional requests.

@rrichardson Both watch create and watch cancel are available with the PR, so I don't get what additional requests are missing?

**Comment by rrichardson** [comment]
>  @rrichardson Both watch create and watch cancel are available with the PR, so I don't get what additional requests are missing? 

I'm really not sure what I was thinking when I wrote that.  Trying to do too many things at once, I reckon.    I agree with the bulk of the PR, I only have some minor nits about the handling of a supplied watch-id. 

I left more sane comments in the PR itself.

**Comment by davidli2010** [comment]
Please see my comments in the PR https://github.com/etcdv3/etcd-client/pull/37#issuecomment-1109900513
