### ISSUE TITLE
SortTarget and SortOrder not declare

### ISSUE THREAD

**Issue by jiashiwen** [etcdv3/etcd-client#38]
hi，when i use request with_sort(),I found SortTarget and SortOrder not declare
etcd-client version is 0.9.1

**Comment by davidli2010** [comment]
[SortTarget](https://docs.rs/etcd-client/0.9.1/etcd_client/enum.SortTarget.html) and [SortOrder](https://docs.rs/etcd-client/0.9.1/etcd_client/enum.SortOrder.html) are all public.
