### ISSUE TITLE
[feature request] Add ability to set connect timeout to client

### ISSUE THREAD

**Issue by joshua-sp** [etcdv3/etcd-client#46]
Currently we can [set the timeout](https://docs.rs/etcd-client/latest/etcd_client/struct.ConnectOptions.html#method.with_timeout) on each request, but it seems that the actual initial connection itself has no timeout, which can lead to hanging if an endpoint is down.

Adding this would probably be a matter of adding a new field to `ConnectOptions` to expose `tonic::transport`'s [connect_timeout](https://docs.rs/tonic/latest/tonic/transport/struct.Endpoint.html#method.connect_timeout) method

**Comment by davidli2010** [comment]
@joshua-sp  The PR #47 add a new API `ConnectOptions::with_connect_timeout()` which can be used to set `connect_timeout`, please review if it meets your requirement.

**Comment by joshua-sp** [comment]
Looks good to me, thanks a lot David!
