### ISSUE TITLE
Determine loss of watch connectivity

### ISSUE THREAD

**Issue by diggyk** [etcdv3/etcd-client#48]
I'm having an issue I need to figure out.  My app starts a watch on start but when testing, I found that if I kill Etcd, the watch just keeps waiting for the next message even though the connection is dead.  I would have expected it to exit with an error.

```
while let Some(msg) = stream.message().await.map_err(econv)? {
            for event in msg.events() {
                println!("Got event of {:?}", event.event_type());
                if let Some(kv) = event.kv() {
                    println!(
                        "  key: {}  val: {}",
                        kv.key_str().map_err(econv)?,
                        kv.value_str().map_err(econv)?
                    );
                }
            }
        }
```

**Comment by diggyk** [comment]
Looks like the way to do this is to poll the watcher with a `progress_request` and then assume it's dead if that request fails.

**Comment by Dreamacro** [comment]
@diggyk Is it `request_progress`? But it doesn't seem to work either
