### ISSUE TITLE
How to avoid the need for copying to obtain a mutable client due to sharing immutable data in a multi-tasking program (or what is the best practice for using this library in a concurrent sharing scenario)?

### ISSUE THREAD

**Issue by ActivePeter** [etcdv3/etcd-client#59]
How to avoid the need for copying to obtain a mutable client due to sharing immutable data in a multi-tasking program (or what is the best practice for using this library in a concurrent sharing scenario)?

In our program we shared a Arc<Context> with a client in it. And some api of client is mutable, so we always clone() the client when we need to call the apis which requires &mut self. Is there better solution?

**Comment by davidli2010** [comment]
The `Client` has already implemented `Clone`, so you are no need to wrap it by `Arc`. 

Besides, you can get `KvClient`, `WatchClient`, etc. They are lightweight and can be concurrenly used in different threads.

**Comment by ActivePeter** [comment]
Thanks.
