### ISSUE TITLE
Default feature set of tonic

### ISSUE THREAD

**Issue by gmilleramilar** [etcdv3/etcd-client#60]
etcd-client depends on `tonic` using its default features:

```
[dependencies]
tonic = "0.9.2"
```
The default features of tonic include A LOT of transitive dependencies, specifically a lot of it comes in through `hyper`.   Would it be possible to put any of that in a feature gate for etcd-client?   I don't know enough about how tonic is used to be able to say.

**Comment by davidli2010** [comment]
The answer is impossible. The default features of tonic are `default = ["transport", "codegen", "prost"]`, and we need all of them.
