### ISSUE TITLE
Support namespace API

### ISSUE THREAD

**Issue by tisonkun** [etcdv3/etcd-client#67]
It's convenient to put/get keys in a "namespace" for separating different usage, or it's even required to smoothly write concurrent tests share the same etcd cluster.

This concept, in ZooKeeper, is named as Chroot. I don't find it in etcd but it should be a client-side feature. I create this issue for discussing whether it's desired to implement in this crate.

The API should affect only the constructors for accepting a chroot parameter/options:

```rust
Client::connect(endpoints, chroot /* String */, options);
Client::connect(endpoints, options); // chroot in options
```

... and all the keys pass to this client will be prepended with the "chroot".

**Comment by davidli2010** [comment]
This crate is just a etcd api wrapper, it does not support features that etcd not support. If `chroot` is a client-side feature, then you can implement a KeyWrapper in your application.

**Comment by tisonkun** [comment]
Make sense. I'll wrap it in the application :D

**Comment by tisonkun** [comment]
And I found that https://github.com/etcdv3/etcd-client/pull/68 is useful to support this feature in client-side - may you take a look? https://github.com/etcdv3/etcd-client/pull/68 should be in the scope of this project.

**Comment by davidli2010** [comment]
> And I found that #68 is useful to support this feature in client-side - may you take a look? #68 should be in the scope of this project.

I have already reviewed it.

**Comment by tisonkun** [comment]
@davidli2010 a possible argue is that etcd's client library implement `namespace` which is exactly what proposed here.

Do you think the `namespace` API is reasonable to be in the scope of this crate?

Ref - https://github.com/etcd-io/etcd/blob/v3.5.10/client/v3/namespace/doc.go

**Comment by davidli2010** [comment]
> @davidli2010 a possible argue is that etcd's client library implement `namespace` which is exactly what proposed here.
> 
> Do you think the `namespace` API is reasonable to be in the scope of this crate?
> 
> Ref - https://github.com/etcd-io/etcd/blob/v3.5.10/client/v3/namespace/doc.go

I'd like to reivew a PR of the `namespace` API.

**Comment by tisonkun** [comment]
@davidli2010 Thanks for your reply! Then let's reopen this issue first, as it's valid.

I'll try to implement it, but it's not on my priority task list, so anyone is open to take it over.
